print("hello world")
a = 5
print(a)
b = int(input())
print(b)
print("a = {} and b = {}".format(a, b))
print("a = {0:d} and b = {1:d}".format(a, b))
print("a = {0:3d} and b = {1:5d}".format(a, b))
print("a = {0:>3d} and b = {1:<5d}".format(a, b))
print("a = {0:03d} and b = {1:05d}".format(a, b))
print("bin = {0:b}, oct = {0:o}, hex = {0:x}".format(12))
print("bin = {1:b}, oct = {1:o}, hex = {0:x}".format(12, 10))
print("bin = {:b}, oct = {:o}, hex = {:x}".format(12, 10, 8))
a, b, c = list(map(int, input().split()))
print(a, b, c)
print("a={:f}".format(123.4567898))
print("a={:8.3f}".format(123.4567898))
